### ISSUE TITLE
Some group output from the tool is incomplete

### ISSUE THREAD

**Issue by brianly** [microsoft/nmarc#2]
When parsing the YAML some items like groups, the parsing is quite complicated. Compare the group_admins element for these groups:

```
groups:
  123456:
    name: Test Group
    id: 123456
    type: internal
    privacy_setting: private
    state: active
    messages_count: 321
    last_message_at: 2020-04-30 22:35:25.506949969 +00:00
    o365_connected: true
    group_admins:
      with_o365_creation_rights: []
      without_o365_creation_rights:
      - mary@fabrikam.com
      - phil@fabrikam.com
    member_counts:
      internal: 91
      external: 0
    uploaded_file_counts:
      yammer_files: 32
      sharepoint_files: 0
  456789:
    name: Test Group 2
    id: 456789
    type: internal
    privacy_setting: private
    state: active
    messages_count: 321
    last_message_at: 2020-04-30 22:35:25.506949969 +00:00
    o365_connected: true
    group_admins: All Yammer Verified admins
    member_counts:
      internal: 91
      external: 0
    uploaded_file_counts:
      yammer_files: 32
      sharepoint_files: 0
```
Sometimes group_admins is a simple string which gets parsed easily with the declarations, but at other times this element is a complex structure. Fixing this requires the creation of an `IYamlTypeConverter` for each of these complicated sections of YAML. 

My first attempt was successful for the `last_date_accessed` element (see LastAccessed and LastAccessedTypeConverter classes.) When I implemented this for the `group_admins` element there were some issues with the internals of YamlDotNet getting out of sync when deserializing. It would overrun into the member_counts when a full file was processed.
